### ISSUE TITLE
Solve Linked List Primitive Operation Problems

### ISSUE THREAD

**Issue by Shivang2003** [Shivang2003/DSA-Problems#1]

**Comment by kapilsingh2003** [comment]
plz Assign....

**Comment by VikasKumar2001** [comment]
plz assign me

**Comment by Shivang2003** [comment]
ok @VikasKumar2001 I have assigned u the task.

**Comment by D-Adarsh** [comment]
With due Respect ...
Kindly assign me this task.
Thank you

**Comment by Shivang2003** [comment]
Ok @D-Adarsh I have assigned u the task.

**Comment by Subhojit666** [comment]
Plzz assign me this task.

**Comment by priyanshuanand166** [comment]
Assign this to me as i am well versed in dsa and i am pretty confident that you will like my merge request.

**Comment by Shivang2003** [comment]
Issue Closed
