### ISSUE TITLE
Perform Singly Linked List Primitive Operations.

### ISSUE THREAD

**Issue by Shivang2003** [Shivang2003/DSA-Problems#10]

**Comment by suresh37** [comment]
Assign me please

**Comment by omprakashchhetri** [comment]
Can you please assign me this Issue !

**Comment by priyanshuanand166** [comment]
Assign this to me as i am well versed in dsa and i am pretty confident that you will like my merge request.

**Comment by Shivang2003** [comment]
Issue Closed
