### ISSUE TITLE
Array

### ISSUE THREAD

**Issue by Shivang2003** [Shivang2003/DSA-Problems#4]
Make a program related to array

**Comment by kapilsingh2003** [comment]
assign me

**Comment by Shivang2003** [comment]
Ok @kapilsingh2003 I have assigned u the task.

**Comment by debi-isha2002** [comment]
assign me

**Comment by priyanshuanand166** [comment]
Assign this to me as i am well versed in dsa and i am pretty confident that you will like my merge request.

**Comment by harshiitsingh** [comment]
Hey @Shivang2003, please assign this issue to me.

**Comment by Shivang2003** [comment]
Issue Closed
