### ISSUE TITLE
Make a program performing basic string operations.

### ISSUE THREAD

**Issue by Shivang2003** [Shivang2003/DSA-Problems#5]

**Comment by kapilsingh2003** [comment]
assign me please

**Comment by Shivang2003** [comment]
Ok @kapilsingh2003 I have assigned u the task.

**Comment by debi-isha2002** [comment]
assign me please

**Comment by cyberpvn7** [comment]
assign me

**Comment by Subhojit666** [comment]
please assign this to me, this is my first contribution

**Comment by Shreenath27** [comment]
Please assign me this issue.

**Comment by cyberpvn7** [comment]
U can PR directly

**Comment by priyanshuanand166** [comment]
Assign this to me as i am well versed in dsa and i am pretty confident that you will like my merge request.

**Comment by codesbysaurav** [comment]
Hello @Shivang2003 Kindly assign the issue to me, I want to contribute in this.

**Comment by Shivang2003** [comment]
Issue Closed
